Still on the runtime problem

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -10,7 +10,7 @@ build=$(cd "$1/" && pwd)
 test -z ${build} && exit
 cache=$(cd "$2/" && pwd)
 test -z ${cache} && exit
-DEFAULT_OTP_VERSION="master"
+DEFAULT_OTP_VERSION="OTP_R15B03-1"
 if [ -f ${build}/.preferred_otp_version ]; then
     OTP_VERSION=$(cat ${build}/.preferred_otp_version)
 fi
@@ -48,7 +48,6 @@ ln -s ${ERLROOT} /app/otp
 ${ERLROOT}/Install -minimal /app/otp
 
 PATH=/app/otp/bin:$PATH
-erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
 export PATH
 unset GIT_DIR
 (
@@ -66,6 +65,10 @@ unset GIT_DIR
     cd ${CB_CACHE_DIR}
     echo "-------> Compiling ChicagoBoss ${cb_ver}"
     ./rebar get-deps compile 2>&1 | sed -u 's/^/       /'
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+      echo "-----> ChicagoBoss Build failed"
+      exit 1
+    fi
 )
 
 cd ${build}
@@ -79,6 +82,7 @@ cp -R ${CB_CACHE_DIR} ${CB_ROOT}
 echo "-------> Compiling App"
 cd ${build}/app
 cp ${CB_ROOT}/rebar .
+erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
 ./rebar get-deps compile 2>&1 | sed -u 's/^/       /'
 if [ ${PIPESTATUS[0]} -ne 0 ]; then
   echo "-----> Build failed"
